### ISSUE TITLE
MML1 and MML2 in Toy example file are the same 

### ISSUE THREAD

**Issue by nmfad** [jordiabante/CpelAsm.jl#12]
Hi Jordi, 

In the toy example output, I am noticing that the MML1 and MML2 files look as follows 

cat example_mml1.bedGraph
chr1	40	90	0.80840009	2	1
chr1	130	155	0.75471698	1	1

cat example_mml2.bedGraph
chr1	40	90	0.21030957	2	1
chr1	130	155	0.16981136	1	1

I see that the last 2 columns of both files have the same values. In the samples I am testing/evaluating for X-skew, the overall ASM output based on P-values seems to be in agreement with the observed skew, but the MML1 and MML2 bedgraph files have the same values in the last 2 columns. Can you explain what do the values in the last 2 columns mean ?? I was under the impression that it is the  average coverage of methylated and unmethylated CpG sites within the 2 haplotypes (MML1 and MML2) respectively. Can you confirm if this is the case ? And if it is why are the values of the columns in both files exactly the same ? I would expect them to be different from one another. Please let me know if I misunderstood anything. Also what is definition of the 3rd column in this file ?? I am trying to understand the outputs from the data and hence the questions. Thank you again for any information you can provide.

**Comment by jordiabante** [comment]
Hi Numrah,

The quantity you want to look at in those bedGraph files is the 4th one, which reflects the mean methylation level (MML) in that particular window. So in this case, the MML in the first window is 0.80840009 for one chromosome and 0.21030957 for the other one. If you look at the differential analysis file you should see that the difference between these two numbers is equal to the differential MML. You can ignore the 4th and 5th columns (they represent number of CpG and subregions, respectively).

Hope this helps!

**Comment by nmfad** [comment]
Thanks much Jordi. This makes a lot of sense now. I noticed that when we lower the cov_ths variable , there are a lot of haplotypes with less than 3 CpG sites in my dataset and it was helpful to eliminate them based on the 4th and 5th column as they maybe noise in the data. I was mistaking them for average coverage of methylated and methylated alleles. But I understand that its basically the number of CpG sites and the number of subregions. Thank you so much for this. 

When you say differential analysis file, which file are you referring to the "example_tmml_pvals.bedGraph" file, is that correct ?
It holds the following values and I see that the 4th column here is the difference between the 2 numbers. 
chr1	40	90	0.59809052	0.00099601593625498

Also can you shed some light on how is the t-test statistic calculated using the 1000 bootstraps ? I tried to understand it using the manuscript and figures and have some idea of it, but I am not sure how the homozygous regions are being used in this process.

**Comment by jordiabante** [comment]
Exactly, the differential analysis files are the tmml, tnme, and pdm files. So the line you are showing has the chromosome, window start, window end, tMML as defined in the paper, and the corresponding adjusted p-value. Homozygous regions are chosen at random where there are no heterozygous SNPs, and an empirical null distribution is constructed by randomly assigning reads to 2 simulated alleles, fitting the models, and then computing the test statistics. This is done 1k times and then the observed statistic at a heterozygous region is compared to this empirical distribution to compute the p-value. Hope this helps!

**Comment by nmfad** [comment]
Thanks a lot Jordi for explaining this! I believe the part I was missing was the random assigning of homozygous reads to 2 simulated alleles. When fitting models to these regions, are you referring to calculating the MML, NME, and PDMs within the homozygous regions similar to the het regions ?? If so, I believe this makes sense to be now. Thanks a lot for clarifying this piece.

**Comment by jordiabante** [comment]
Pretty much, yes. By that, I mean fitting the Ising model discussed in the paper, from which we can obtain the MML, NME, and PDM values. I will go ahead and close this issue if that's okay, but let me know if you had any other issues or questions. Thanks!

**Comment by nmfad** [comment]
Thanks a lot Jordi for your responses. The results I have from the datasets I am using look pretty good from CPEL and understanding the outputs has been very helpful. I will let you know if other questions come up. Thanks again!
