### ISSUE TITLE
How to create the example.a1.bam and example.a2.bam?

### ISSUE THREAD

**Issue by ifishlin** [jordiabante/CpelAsm.jl#6]
I'm very confused about the origin of the two bam files in the toyExample. Based on the bismark_reports, the bam came from aligning PE reads to two haplotypes separately. I assume there should be a process to divide reads into two groups (correspond to two haplotypes), but two bams have the same aligned reads (396 reads).

For example, the read "EASX:X:X:X:X:33:33_1:Y:0:NNNNNN" appear in two bam files. Is it correct? Any read should only have one origin.

Can you share how to create two bam files? thanks

**Comment by jordiabante** [comment]
Each BAM file was simulated using a simple in-house script that uses the same read names every time it generates a BAM file. Also, we generated the same number of reads for each "haplotype", hence the same number of aligned reads in both BAM files. Lastly, the data for allele 1 & 2 was generated from a Bernoulli independent model with p=0.8 and p=0.2, respectively, which you will be able to see in the output. In reality, however, the read names will differ, like you suggest, and the total number of aligned reads will most likely be different as well. This does not matter for the toy example provided with the package though. Hope this helps!
