### ISSUE TITLE
Julia Version

### ISSUE THREAD

**Issue by Tschichen** [jordiabante/CpelAsm.jl#7]
Dear CpelASM Team,

I really would like to run your software on my datasets, but unfortunately, it does not run under the latest Julia version on my device. Moreover, I can not find Julia in the version 1.3.0 that is recommended in the ReadMe. Could you give me a hint with which version of Julia I may have success or what I might overlooked?

Thanks in advance, Christiane

**Comment by jordiabante** [comment]
Hi Christiane,

Happy to help. Can you try running it with any 1.3.X version of julia and let me know if that does the trick?

Thanks!
- jordi
