### ISSUE TITLE
 How to implement parallel computing?

### ISSUE THREAD

**Issue by sjbxzpf** [jordiabante/CpelAsm.jl#9]
Dear CpelAsm Team,

In the original text, you mentioned: "Note, however, that the clear superiority of the CPEL method over existing methods comes at a substantial computational cost (it took about 48 hours using 20 CPUs to process one WGBS sample in the real data), which necessitates the use of parallel processing using a computer cluster." However, when I run CpelAsm, it appears to use only one CPU. Due to my limited familiarity with the Julia language, could you please guide me on how to enable parallel processing? Thank you very much.

**Comment by jordiabante** [comment]
Hi, that is correct. Unfortunately, CpelAsm currently does not support parallel computing (it probably won't in the future either). What we did in our case was to simply process each chromosome independently, and that's where you gain the 20x speedup. It's as simple as splitting the reference and VCF files. Hope this helps!

**Comment by sjbxzpf** [comment]
> Hi, that is correct. Unfortunately, CpelAsm currently does not support parallel computing (it probably won't in the future either). What we did in our case was to simply process each chromosome independently, and that's where you gain the 20x speedup. It's as simple as splitting the reference and VCF files. Hope this helps!
thanks
